-- Example config in lua
-- vim.g.nord_contrast = true
-- vim.g.nord_borders = true
-- vim.g.nord_disable_background = true
-- nord_enable_sidebar_background = true
-- vim.g.nord_italic = false
-- vim.g.nord_uniform_diff_background = true
-- vim.g.nord_bold = false
-- vim.g.nord_cursorline_transparent = true

-- Load the colorscheme
-- require('nord').set()
